// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package sui.rpc.v2beta2;

import "sui/rpc/v2beta2/object_reference.proto";

// Input for programmable transactions
message Input {
  oneof input {
    ObjectInput object = 1;
    PureInput pure = 2;
    ReceiverArgument receiver = 3;
  }
}

// Transaction input
message TransactionInput {
  oneof input {
    ObjectInput object = 1;
    PureInput pure = 2;
    ReceiverArgument receiver = 3;
  }
}

message ObjectInput {
  oneof object {
    ImmutableOrOwnedObject immutable_or_owned = 1;
    SharedObject shared = 2;
  }
}

message ImmutableOrOwnedObject {
  optional ObjectReference object_ref = 1;
}

message SharedObject {
  optional string object_id = 1;
  optional uint64 initial_shared_version = 2;
  optional bool mutable = 3;
}

message PureInput {
  optional bytes value = 1;
}

message ReceiverArgument {}